name: Save Results
on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read
    id-token: write
    pages: write
jobs:
    run_vite:
        runs-on: ubuntu-latest
        steps:
            - name: Download Code
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "24"

            - name: Install Dependencies
              working-directory: Class_08_27/counter
              run: npm install

            - name: Run Vite Build
              working-directory: Class_08_27/counter
              run: npm run build
            - name: Configure Github Pages
              uses: actions/configure-pages@v5
            - name: Save Zip File
              uses: actions/upload-pages-artifact@v4
              with:
                  name: counter-build
                  path: Class_08_27/counter/dist

            - name: Deploy to Github Pages
              uses: actions/deploy-pages@v4
