name: Hello World
on:
  workflow_dispatch:
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World!"
      - name: Download Code
        uses: actions/checkout@v3
      - name: Where am I?
        run: pwd
      - name: List Files
        run: ls -la
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"
      - name: Node.js version
        run: node -v
      - name: Install Dependencies
        run: npm install
      - name: Run Eslint
        run: npm run check:js
